#!/bin/bash

ARCH=$(uname -m)
if [[ "$ARCH" != "aarch64" ]]; then
    echo "Only works for Aarch64 assembly"
    exit 1
fi

if [ $# -ne 1 ]; then
    echo "Usage: gqz <filename>.blu"
    exit 1
fi

INPUT_FILE=$(realpath "$1")
if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: File '$INPUT_FILE' not found."
    exit 1
fi

PROJECT_DIR="/home/h3m/Desktop/Projects/Groquaza-compiler/scripts"
cd "$PROJECT_DIR" || { echo "Project directory not found"; exit 1; }
./build.sh "$INPUT_FILE"
cd ../src

if [ ! -f output.s ]; then
    echo "Error: Assembly file output.s was not generated by the compiler."
    exit 1
fi

BUILD_DIR=$(mktemp -d)
ASM_FILE="$BUILD_DIR/output.s"
OBJ_FILE="$BUILD_DIR/output.o"
RUNTIME_OBJ="$BUILD_DIR/runtime.o"
FINAL_EXE="$BUILD_DIR/final_output"

mv output.s "$ASM_FILE"
as -o "$OBJ_FILE" "$ASM_FILE" || { echo "Assembly failed"; exit 1; }
gcc -c runtime/runtime.c -o "$RUNTIME_OBJ" -std=c11 || { echo "Runtime compilation failed"; exit 1; }
gcc -o "$FINAL_EXE" "$OBJ_FILE" "$RUNTIME_OBJ" -nostartfiles -lc || { echo "Linking failed"; exit 1; }
"$FINAL_EXE"
rm -rf "$BUILD_DIR"
